cart/urls.py
from django.urls import path
from .views import cart_toggle, update_cart, refresh_total, CartListView

urlpatterns = [
    path('', CartListView.as_view(), name='cart-list'),
    path('ajax/toggle/', cart_toggle, name='cart-toggle'),
    path('update/', update_cart, name='cart-update'),
    path('totals/', refresh_total, name='cart-refresh'),
]

checkout/urls.py
from django.urls import path
from .views import OrderCreateView, OrderDetailView, OrderListView, cache_data
from .webhooks import webhook

urlpatterns = [
    path('', OrderCreateView.as_view(), name='order-create'),
    path('order/<int:pk>/',
         OrderDetailView.as_view(), name='order-detail'),
    path('orders/',
         OrderListView.as_view(), name='order-list'),
    path('cache_data/', cache_data, name='cache-data'),
    path('webhook/', webhook, name='webhook'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Handlers for custom error pages
handler404 = 'config.views.custom_page_not_found'
handler403 = 'config.views.custom_permission_denied'
handler400 = 'config.views.custom_bad_request'
handler500 = 'config.views.custom_server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('contact/', include(('contact.urls', 'contact'),
                             namespace='contact')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('checkout/',
         include(('checkout.urls', 'checkout'), namespace='checkout')),
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('', include(('products.urls', 'products'), namespace='products')),
    path('users/', include(('users.urls', 'users'),
                           namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import (CategoryDetailView,
                    ProductListView,
                    ProductDetailView,
                    StockDropDetailView)

urlpatterns = [
    path('', ProductListView.as_view(), name="product-list"),
    path('category/<int:pk>/',
         CategoryDetailView.as_view(),
         name="category-detail"),
    path('product/<int:pk>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('stockdrop/<int:pk>/',
         StockDropDetailView.as_view(),
         name="stockdrop-detail"),
]

cart/models.py
# Create your models here.

cart/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.template import RequestContext
from django.contrib import messages

from django_ajax.decorators import ajax

from config import settings
from products.models import Product

from decimal import Decimal


class CartListView(ListView):
    """View that displays all the products in the cart as a list."""
    model = Product
    context_object_name = 'products'
    template_name = 'cart/cart_list.html'


@ajax
def cart_toggle(request):
    """Add or removes the specified product to the shopping cart.
    The view is Ajaxed, so it is only called by a JS file.
    It runs through numerous variables such as item stock,
    whether the item is unique, etc, before giving a response.
    The decorator converts the response to JSON format.
    It is then picked up by the JS file which completes the page effects.
    'tag' and 'message' are used to display the toasts.
    'result' and 'special' are used to define the logic on the JS side."""

    if request.is_ajax and request.method == "POST":
        # Runs through a number of variables to process the ajax call.
        # If it fails, it throws an exception with a message.
        try:
            # Tries to retrieve the item and quantity,
            # if no item was given it is set to '0' to throw an error.
            item_id = request.POST.get('item-id', '0')
            product = get_object_or_404(Product, pk=item_id)
            quantity = int(request.POST.get('quantity'))

            # Gets the cart to run through item details.
            cart = request.session.get('cart', {})

            # 'update' is sent when product quantity is being changed.
            # Despite the 'uncart' result variable it doesn't uncart but
            # actually updates quantity on the cart list page.
            if request.POST.get('special') == 'update':
                cart[item_id] = quantity

                # Checks stock and if the quantity requestd is greater,
                # it sets it to the max available.
                if cart[item_id] > product.stock:
                    cart[item_id] = product.stock
                request.session['cart'] = cart

                # Defines the variables to be sent the JS file.
                tag = 'success'
                message = f'Updated {product.name} quantity to \
                    {cart[item_id]}.'
                result = 'uncarted'

            # Removes items from the cart if it is a once-off unique item or
            # if the remove button is clicked on the cart list page.
            elif (item_id in list(cart.keys()) and product.is_unique) or (
                    request.POST.get('special') == 'remove'):
                cart.pop(str(item_id))

                request.session['cart'] = cart
                tag = 'info'
                message = f'Removed {product.name} from your cart.'
                result = 'uncarted'

            # If the product is not a once-off item and is already in the cart,
            # hitting the 'add to cart' button will increase quantity by one.
            elif item_id in list(cart.keys()) and not product.is_unique:
                cart[item_id] += quantity
                if cart[item_id] > product.stock:
                    cart[item_id] = product.stock

                request.session['cart'] = cart
                tag = 'success'
                message = f'Updated {product.name} quantity to \
                    {cart[item_id]}.'
                result = 'uncarted'

            # If the other conditions aren't true it is a simple add to cart.
            else:
                cart[item_id] = quantity
                if cart[item_id] > product.stock:
                    cart[item_id] = product.stock

                request.session['cart'] = cart
                tag = 'success'
                message = f'Added {product.name} to your cart.'
                result = 'carted'

        # If none of the conditions are true, it throws an error.
        except Exception as e:
            result = 'error'
            tag = 'warning'
            message = f'Error adding item to cart: {e}'

        # If there is a special case in the POST data,
        # it gets passed to the JS file for its logic.
        # Else, it sends the variables declare in the 'if' clauses.
        if 'special' in request.POST:
            special = request.POST.get('special')
            return {'message': message, 'result': result, 'tag': tag,
                    'special': special}
        else:
            return {'message': message, 'result': result, 'tag': tag}


def update_cart(request):
    """This view is used to update the cart_popover.html template.
    It is called by the JS file after it successfully recieves
    the cart_toggle view response.
    It updates the context using the same logic as the get_cart context
    processor before refreshing the template.
    The JS script then pushes the newly rendered template into
    the popover HTML."""

    # Declares variables for use with the cart.
    cart = request.session.get('cart')
    cart_items = []
    cart_total = 0
    cart_quantity = 0

    if cart:
        # Creates a copy of the cart dictionary for iteration:
        temp_cart = cart.copy()
        for item_id, item_data in temp_cart.items():
            # Sets the total quantity of an item:
            cart_quantity += item_data

            # Confirms the item is valid or throws an error with a message:
            try:
                product = Product.objects.get(pk=item_id)
            except Product.DoesNotExist:
                # Declares product as false and removes it:
                product = False
                cart.pop(item_id)
                messages.warning(request,
                                 'A Product is unavailable.')

            # If the product is valid and in stock,
            # it calculates details for that item:
            if product is not False:
                if product.stock >= 1:
                    cart_total += item_data * product.price
                    cart_items.append({
                        'item_id': item_id,
                        'quantity': item_data,
                        'product': product})

                # Or else the item is removed from the cart with feedback:
                else:
                    cart.pop(item_id)
                    messages.warning(request,
                                     f'{product} has run out of stock!')

            # Skips the product if it is not False:
            else:
                pass

    # Checks the cart total price and declares delivery price accordingly.
    # The FREE_DELIVERY_THRESHOLD is a set price declared in settings.
    if cart_total < settings.FREE_DELIVERY_THRESHOLD and cart_total > 0:
        delivery = Decimal(settings.STANDARD_DELIVERY)
    else:
        delivery = 0

    grand_total = cart_total + delivery
    request.session.save()

    # Calculates the grand total and then pushes all details into the context.
    RequestContext(request).push({'cart': cart,
                                  'cart_quantity': cart_quantity,
                                  'cart_items': cart_items,
                                  'cart_total': cart_total,
                                  'delivery': delivery,
                                  'grand_total': grand_total})

    # Re-renders the popover template
    return render(request, 'cart/includes/cart_popover.html')


def refresh_total(request):
    """One the cart list page, this refreshes the totals box template.
    Other context info is handled by the update_crt view."""

    return render(request, 'cart/includes/totals.html')

templates/cart/includes/box_cart_toggle.html
{% load static %}
<!--This is the button that appears on the product_box.html template.
The toggle-form class makes it a target for the ajax functions..-->
<form class="col-2 text-center px-0 ml-auto toggle-form" id="cf-{{ product.id }}" action="{% url 'cart:cart-toggle' %}" method="POST">
    {% csrf_token %}
    <!--It only sends the product ID and always a quantity of 1.-->
    <input type="hidden" name="item-id" value="{{ product.id }}" />
    <input type="hidden" name="quantity" value="1" />
    <!--Selects the default icon based on whether the item is in the cart or not.
    object tags are used to display the SVG for caching.-->
    <button type="submit" class="btn btn-link p-0 h-100 w-100">
        {% if product.id|stringformat:'s' in cart %}
        <object class="box-object" id="cart-svg-{{ product.id }}" type="image/svg+xml" data="{% static 'icons/cart-check.svg' %}">
            <img id="cart-img-{{ product.id }}" src="{% static 'icons/cart-check.svg' %}" alt="Add to Cart" />
        </object>
        {% else %}
        <object class="box-object" id="cart-svg-{{ product.id }}" type="image/svg+xml" data="{% static 'icons/cart-plus.svg' %}">
            <img id="cart-img-{{ product.id }}" src="{% static 'icons/cart-plus.svg' %}" alt="Add to Cart" />
        </object>
        {% endif %}
    </button>
</form>

templates/cart/includes/cart_popover.html
{% load static %}
<!--All content with the data-title and data-content must be escaped.-->
<a
    class="d-inline-block href-stop"
    id="cart-popover"
    href="#"
    data-toggle="popover"
    data-trigger="focus"
    data-placement="bottom"
    data-html="true"
    {% if cart_quantity %}
    data-title="{% include 'cart/includes/cart_popover_title.html' %}"
    data-content="{% include 'cart/includes/cart_popover_content.html' %}"
    {% else %}
    data-title="Empty Cart"
    data-content="Hope you find something you like!"
    {% endif %}
    tabindex="0"
>
    <!--Selects the default icon based on whether the item is in the cart or not.
    Includes alittle badge that updates with cart quantity.
    object tags are used to display the SVG for caching.-->
    {% if cart_quantity %}
    <object class="header-object" type="image/svg+xml" data="{% static 'icons/cart-fill.svg' %}">
        <img src="{% static 'icons/cart-fill.svg' %}" alt="Account" />
    </object>
    <span class="badge badge-secondary rounded-circle mb-1">{{ cart_quantity }}</span>
    {% else %}
    <object class="header-object" type="image/svg+xml" data="{% static 'icons/cart.svg' %}">
        <img src="{% static 'icons/cart.svg' %}" alt="Account" />
    </object>
    {% endif %}
</a>

templates/cart/includes/cart_popover_content.html
{% load static %}
&lt;!--All content must be escaped. Displays items in the cart with a total. Else it displays an empty cart message.--&gt;
&lt;div class=&quot;list-group border-0&quot;&gt;
    {% for item in cart_items %}
    &lt;a class=&quot;list-group-item border-0 mx-0 my-1 p-1 w-100&quot; href=&quot;{% url 'products:product-detail' item.product.id %}&quot;&gt;
        &lt;img src=&quot;{{ item.product.image.url }}&quot; class=&quot;img-fluid float-left pr-1 like-thumb&quot; alt=&quot;{{ item.product.name }}&quot; /&gt;
        &lt;p class=&quot;d-inline-block pb-0 mb-0 float-right&quot;&gt;{{ item.product.name|truncatechars:'15' }} &lt;span class=&quot;text-dark&quot;&gt; | {{ item.quantity }} x &euro;{{ item.product.price }}&lt;/span&gt;&lt;/p&gt;
    &lt;/a&gt;
    {% endfor %} {% if delivery != 0 %}
    &lt;p class=&quot;list-group-item border-0 mx-0 my-1 p-1&quot;&gt;
        &lt;strong&gt;&lt;span class=&quot;float-left&quot;&gt;Delivery&lt;/span&gt;&lt;/strong&gt; &lt;span class=&quot;float-right&quot;&gt;| &euro;{{ delivery|floatformat:2 }}&lt;/span&gt;
    &lt;/p&gt;
    &lt;p class=&quot;list-group-item border-0 mx-0 my-1 p-1&quot;&gt;
        &lt;strong&gt;&lt;span class=&quot;float-left&quot;&gt;Free Delivery above &euro;60 spend&lt;/span&gt;&lt;/strong&gt;
    &lt;/p&gt;
    {% else %}
    &lt;p class=&quot;list-group-item border-0 mx-0 my-1 p-1&quot;&gt;
        &lt;strong&gt;&lt;span class=&quot;float-left&quot;&gt;Delivery&lt;/span&gt;&lt;/strong&gt; &lt;span class=&quot;float-right&quot;&gt;| Free!&lt;/span&gt;
    &lt;/p&gt;
    {% endif %}
    &lt;p class=&quot;list-group-item border-0 mx-0 my-1 p-1&quot;&gt;
        &lt;strong&gt;&lt;span class=&quot;float-left&quot;&gt;Total&lt;/span&gt;&lt;/strong&gt; &lt;span class=&quot;float-right&quot;&gt;| &euro;{{ grand_total }}&lt;/span&gt;
    &lt;/p&gt;
&lt;/div&gt;

templates/cart/includes/cart_popover_title.html
&lt;!--All content must be escaped. Displays an option to go to the cart or checkout.--&gt;
&lt;div class=&quot;text-center&quot;&gt;
    &lt;a class=&quot;text-white&quot; href=&quot;{% url 'cart:cart-list' %}&quot;&gt;&lt;p class=&quot;btn btn-primary mb-0&quot;&gt;Go to Cart&lt;/p&gt;&lt;/a&gt;
    |
    &lt;a class=&quot;text-white&quot; href=&quot;{% url 'checkout:order-create' %}&quot;&gt;&lt;p class=&quot;btn btn-secondary mb-0&quot;&gt;Secure Checkout&lt;/p&gt;&lt;/a&gt;
&lt;/div&gt;

templates/cart/includes/cart_product_display.html
{% load static %}
<!--Template used to display cart items in the cart_list.html template.-->
<div id="cart-item-{{ item.product.id }}">
    <article class="row mx-0">
        <!--Provides an image with a link to the product.
        the cart-thumb class controls the size.-->
        <div class="col-3 col-md-2 py-0 px-1 px-sm-3 px-md-4">
            <a href="{% url 'products:product-detail' item.product.id %}">
                <img src="{{ item.product.image.url }}" class="img-fluid cart-thumb" alt="{{ item.product.name }}" />
            </a>
        </div>
        <div class="col-9 col-md-10">
            <div class="row pl-2">
                <!--Displays the item name, truncating longer text on smaller devices.-->
                <h6 class="col d-md-none text-primary heading-font mx-1 p-0"><a href="{% url 'products:product-detail' item.product.id %}">{{ item.product.name|truncatechars:"15" }}</a></h6>
                <h6 class="col d-none d-md-block text-primary heading-font mr-1 p-0 pl-1"><a href="{% url 'products:product-detail' item.product.id %}">{{ item.product.name }}</a></h6>
                <div class="col-4 col-md-2 px-0 text-right">
                    <div class="row mx-0">
                        <!--Displays prize and size if the item has one.-->
                        <p class="col-12 text-dark p-0 pr-2 pr-md-1">€{{ item.product.price }}</p>
                        {% if item.product.size %}
                        <p class="col-12 text-dark p-0 pr-2 pr-md-1">Size: {{ item.product.size }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row pl-2">
                <!-- Displays the product description and the button layout on larger screens.-->
                <p class="col d-none d-md-block text-dark mb-1 pl-1">{{ item.product.description }}</p>
                <form class="col-5 d-none d-md-block mr-1 p-0 text-right toggle-form" id="af-{{ item.product.id }}" action="{% url 'cart:cart-toggle' %}" method="POST">
                    {% csrf_token %}
                    <!--Shows buttons appropriately based on item type.
                    Items can be removed from the cart.
                    Allows for quantity to be updated if there is numerous stock.-->
                    <input type="hidden" name="item-id" value="{{ item.product.id }}" />
                    {% if item.product.is_unique %}
                    <input type="hidden" name="quantity" value="1" />
                    {% else %}
                    <div class="form-label-group d-inline-block align-bottom mb-0 mx-1">
                        <input class="form-control mt-1 pt-4" type="number" name="quantity" value="{{ item.quantity }}" min="1" max="{{ item.product.stock }}" />
                        <label class="py-0 pl-0 pr-3" for="cart-quantity-{{ item.product.id }}">Quantity</label>
                    </div>
                    <button id="up-{{ item.product.id }}" type="submit" class="update-button btn-sm btn-dark px-1 mx-1">Update</button>
                    {% endif %}
                    <button id="re-{{ item.product.id }}" type="submit" class="remove-button btn-sm btn-dark px-1 mx-1">Remove</button>
                </form>
                <!--Displays a different button layout for smaller screens.-->
                <form class="col d-md-none mr-1 p-0 text-right toggle-form" id="bf-{{ item.product.id }}" action="{% url 'cart:cart-toggle' %}" method="POST">
                    {% csrf_token %}
                     <!--Shows buttons appropriately based on item type.
                    Items can be removed from the cart.
                    Allows for quantity to be updated if there is numerous stock.-->
                    <input type="hidden" name="item-id" value="{{ item.product.id }}" />
                    {% if item.product.is_unique %}
                    <input type="hidden" name="quantity" value="1" />
                    {% else %}
                    <div class="form-label-group d-inline-block align-top">
                        <input class="form-control pt-4" type="number" name="quantity" value="{{ item.quantity }}" min="1" max="{{ item.product.stock }}" />
                        <label class="py-0 pl-0" for="cart-quantity-{{ item.product.id }}">Quantity</label>
                    </div>
                    <button id="us-{{ item.product.id }}" type="submit" class="update-button btn-sm btn-dark px-1">Update</button>
                    {% endif %}
                    <button id="rs-{{ item.product.id }}" type="submit" class="remove-button btn-sm btn-dark px-1">Remove</button>
                </form>
            </div>
        </div>
    </article>
    <hr class="my-3" />
</div>

templates/cart/includes/detail_cart_toggle.html
{% load static %}
<!--This is the button that appears on the product_box.html template.
The toggle-form class makes it a target for the ajax functions.
If the item has numerous stock option the product_detail.html template displays a quantity selection box.
This box is linked to this form and does not appear in this template.-->
<form class="col-10 col-sm-8 col-md-9 col-lg-7 pl-0 toggle-form" id="cf-{{ product.id }}" action="{% url 'cart:cart-toggle'%}" method="POST">
    {% csrf_token %}
    <!--Always sends the product id.
    If the product is unique it automatically sends 1 as the quantity.
    It send the 'special=stocked' value for other items for logic in the ajax JS and views.-->
    <input type="hidden" name="item-id" value="{{ product.id }}" />
    {% if product.is_unique %}
    <input type="hidden" name="quantity" value="1" />
    {% else %}
    <input type="hidden" name="special" value="stocked" />
    {% endif %}
    <button type="submit" id="btn-{{ product.id }}" class="btn-lg btn-dark w-100">
        <!--Selects the default icon based on whether the item is in the like context or not.
        object tags are used to display the SVG for caching.-->
        {% if product.id|stringformat:'s' in cart and product.is_unique %}
        <object class="detail-object" id="cart-svg-{{ product.id }}" type="image/svg+xml" data="{% static 'icons/cart-check-white.svg' %}">
            <img id="cart-img-{{ product.id }}" src="{% static 'icons/cart-check-white.svg' %}" alt="Add to Cart" />
        </object>
        &nbsp;&nbsp;Remove from Cart {% else %}
        <object class="detail-object" id="cart-svg-{{ product.id }}" type="image/svg+xml" data="{% static 'icons/cart-plus-white.svg' %}">
            <img id="cart-img-{{ product.id }}" src="{% static 'icons/cart-plus-white.svg' %}" alt="Add to Cart" />
        </object>
        &nbsp;&nbsp;Add to Cart {% endif %}
    </button>
</form>

templates/cart/includes/totals.html
<!--A template which displays the cart total and delivery cost on the cart_list page.-->
<div class="row mx-0">
    <div class="col text-right">
        <p class="col">Delivery:</p>
    </div>
    <div class="col-3 col-md-2 px-0 text-right">
    <!--Adjusts cart delivery cost based on total.-->
        {% if cart %}
            {% if delivery != 0 %}
            <p class="text-dark p-0 pr-2 pr-md-1"><strong>€{{ delivery|floatformat:2 }}</strong></p>
            {% else %}
            <p class="text-dark p-0 pr-2 pr-md-1"><strong>Free!</strong></p>
            {% endif %}
        {% else %}
            <p class="text-dark p-0 pr-2 pr-md-1"><strong>Cart is empty.</strong></p>
        {% endif %}
    </div>
</div>
<div class="row mx-0">
    <div class="col text-right">
        <p class="col">Total:</p>
    </div>
    <!--Displays the current delivery total.-->
    <div class="col-3 col-md-2 px-0 text-right">
        <p class="text-dark p-0 pr-2 pr-md-1"><strong>€{{ grand_total }}</strong></p>
    </div>
</div>