cart/urls.py
from django.urls import path
from .views import cart_toggle, update_cart, refresh_total, CartListView

urlpatterns = [
    path('', CartListView.as_view(), name='cart-list'),
    path('ajax/toggle/', cart_toggle, name='cart-toggle'),
    path('update/', update_cart, name='cart-update'),
    path('totals/', refresh_total, name='cart-refresh'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Handlers for custom error pages
handler404 = 'config.views.custom_page_not_found'
handler403 = 'config.views.custom_permission_denied'
handler400 = 'config.views.custom_bad_request'
handler500 = 'config.views.custom_server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('contact/', include(('contact.urls', 'contact'),
                             namespace='contact')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('checkout/',
         include(('checkout.urls', 'checkout'), namespace='checkout')),
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('', include(('products.urls', 'products'), namespace='products')),
    path('users/', include(('users.urls', 'users'),
                           namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import (CategoryDetailView,
                    ProductListView,
                    ProductDetailView,
                    StockDropDetailView)

urlpatterns = [
    path('', ProductListView.as_view(), name="product-list"),
    path('category/<int:pk>/',
         CategoryDetailView.as_view(),
         name="category-detail"),
    path('product/<int:pk>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('stockdrop/<int:pk>/',
         StockDropDetailView.as_view(),
         name="stockdrop-detail"),
]

products/models.py
import contextlib
import sys
from io import BytesIO

from django.contrib.postgres import fields
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.db import models
from django.utils import timezone
from PIL import Image

from config import settings


class Category(models.Model):
    """Defines categories to apply to products.
    A simple model to group products."""

    name = models.CharField(max_length=254)
    friendly_name = models.CharField(max_length=254, default='')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    """Defines the Product Class. Many fields are optional.
    A default image is uploaded if no image is selected.
    Images will be resized on upload to 500x500px square shape.
    I would recommend cropping your images to a 1:1 ratio first.
    It automatically sets stock values based on is_uniqe value.
    Generates the 'popuarity' value on save.This value is a combination of the
    total quantity an item was sold and how many unique users have liked it."""

    category = models.ForeignKey(
        'Category',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='products',
    )
    stock_drop = models.ForeignKey(
        'StockDrop',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='products',
    )

    name = models.CharField(max_length=254, default='')
    description = models.TextField()
    size = models.CharField(max_length=2, default='', blank=True)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(
        default=f'{settings.BUCKET_NAME}/default.png',
        upload_to='product_images',
    )
    date_added = models.DateTimeField(default=timezone.now)
    admin_tags = fields.ArrayField(models.CharField(max_length=40), size=8)
    is_unique = models.BooleanField(default=True, blank=False, null=False)
    stock = models.SmallIntegerField(default=1, blank=False, null=False)
    times_purchased = models.IntegerField(
        default=0, blank=False, null=False, editable=False
    )
    popularity = models.IntegerField(
        default=0, blank=False, null=False, editable=False
    )

    class Meta:
        ordering = ['-popularity']

    def __str__(self):
        return f'{self.name}: €{self.price}'

    def save(self, *args, **kwargs):
        """Generates default stock values.
        Will restock items that are not unique.
        Updates the 'popularity' value.
        Image resizing, snippet repurposed from:
        https://djangosnippets.org/snippets/10597/"""

        # Declares a check to see if the product exists.
        this_object = None
        try:
            this_object = Product.objects.get(pk=self.id)
        except Product.DoesNotExist:
            pass
        finally:
            # Updates popularity (See below)
            self._update_popularity(self, *args, **kwargs)

            # Sets default stock to 50 and/or restocks non-unique items
            if not self.is_unique and self.stock == 1:
                self.stock = 50

            # Prevents images from being copied on every save
            # will save a new copy on an upload
            if (
                (this_object and self.image.name != this_object.image.name)
                or (not this_object)
                and (self.image.name != f'{settings.BUCKET_NAME}/default.png')
            ):
                # opens the image before it is saved.
                img = Image.open(self.image)
                img_format = img.format.lower()

                # Image is resized
                output_size = (500, 500)
                img = img.resize(size=(output_size))

                # Converts format while in memory
                output = BytesIO()
                img.save(output, format=img_format)
                output.seek(0)

                # Replaces the Imagefield value with the newly converted image
                self.image = InMemoryUploadedFile(
                    output,
                    'ImageField',
                    f'{self.image.name.split(".")[0]}.{img_format}',
                    'image/jpeg',
                    sys.getsizeof(output),
                    None,
                )
                super().save(*args, **kwargs)
            else:
                super().save(*args, **kwargs)

    def _update_popularity(self, *args, **kwargs):
        """Used for item ordering so more popular items are displayed first.
        A combination of total unique likes and number sold."""
        with contextlib.suppress(ValueError):
            self.popularity = self.users.count() + self.times_purchased


class StockDrop(models.Model):
    """Allows for the creation of a collection of Products.
    You can add a splash image which will be resized and a blurb.
    Images will be resized on upload to 1289x480px square shape.
    I would recommend cropping your images to a 8:3 ratio first."""

    name = models.CharField(max_length=30, null=False)
    description = models.CharField(max_length=200, null=False)
    image = models.ImageField(upload_to='stock_drop')
    date_added = models.DateTimeField(default=timezone.now)
    display = models.BooleanField(default=True)

    def save(self, *args, **kwargs):
        """Image resizing, snippet repurposed from:
        https://djangosnippets.org/snippets/10597/"""
        # Opening the image
        this_object = None
        try:
            this_object = StockDrop.objects.get(pk=self.id)
        except StockDrop.DoesNotExist:
            pass
        finally:
            # Prevents images from being copied on every save
            # will save a new copy on an upload
            if (this_object and self.image.name != this_object.image.name) or (
                not this_object
            ):
                img = Image.open(self.image)
                img_format = img.format.lower()
                # Image is resized
                output_size = (1280, 480)
                img = img.resize(size=(output_size))

                # Converts format while in memory
                output = BytesIO()
                img.save(output, format=img_format)
                output.seek(0)

                # Replaces the Imagefield value with the newly converted image
                self.image = InMemoryUploadedFile(
                    output,
                    'ImageField',
                    f'{self.image.name.split(".")[0]}.{img_format}',
                    'image/jpeg',
                    sys.getsizeof(output),
                    None,
                )

                super().save(*args, **kwargs)
            else:
                super().save(*args, **kwargs)

    class Meta:
        """Orders by the most recent created by default."""

        ordering = ['-date_added']

    def __str__(self):
        return f'{self.date_added.strftime("%B")}: {self.name}'

products/views.py
from django.contrib import messages
from django.core.paginator import Paginator
from django.views.generic import ListView, DetailView
from django.contrib.postgres.search import (SearchQuery,
                                            SearchRank,
                                            SearchVector)

from .models import Category, Product, StockDrop


class ProductListView(ListView):
    """Renders the home page with a Products List.
    If there is a GET request, performs a search."""
    model = Product
    context_object_name = 'products'

    def get_queryset(self):
        """Returns either all Products or a query appropriately."""
        if 'query' in self.request.GET:
            # Returns all products if there's no query
            if self.request.GET['query'] == '':
                messages.warning(self.request,
                                 "You didn't search for anything")
                return Product.objects.all().order_by('-stock', '-popularity')
            else:
                # Performs a full text search using Postgres database
                # functionality, weighting tags above other text.
                self.user_query = self.request.GET['query']
                self.vector = SearchVector(
                    'name',
                    'description',
                    'category',
                    weight='B') + SearchVector(
                        'admin_tags', weight='A')
                self.query = SearchQuery(self.user_query)
                self.rank = SearchRank(self.vector, self.query)

                # Returns search results in order of rank,
                # removing items with no rank.
                return Product.objects.annotate(
                    rank=self.rank).order_by(
                    '-rank').filter(rank__gt=0)
        else:
            return Product.objects.all().order_by('-stock', '-popularity')

    def get_context_data(self, **kwargs):
        """Adds all necessary information to the context"""
        context = super().get_context_data(**kwargs)
        # Selects the active tab
        if 'query' not in self.request.GET and self.request.path == '/':
            all_products_active = True
            context['all_products_active'] = all_products_active

        # Paginates products for the infinite scroll feature.
        products = context['products']
        paginator = Paginator(products, 9)
        page_number = self.request.GET.get('page')

        # Pagination is more complicated with a query
        # so this is necessary for the products to display properly and
        # not repeat the first page infinitely.
        if 'query' in self.request.GET:
            if 'page' in self.request.GET['query']:
                page_number = self.request.GET['query'].rpartition('=')[-1]
            keyword = self.request.GET['query'].split('?')[0]
            context['keyword'] = keyword

        page_obj = paginator.get_page(page_number)

        # If there are no products, return all products
        if products.count() == 0:
            context['products'] = Product.objects.all().order_by(
                '-stock', '-popularity')[:9]

        context['page_obj'] = page_obj

        return context


class ProductDetailView(DetailView):
    """Renders the product detail page."""
    model = Product
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        """Adds all necessary information to the context"""
        context = super().get_context_data(**kwargs)
        # Selects the active tab
        categories_active = True

        selected_product = context['product']
        selected_category = selected_product.category

        # Renders related products from the same category
        # while removing the current product.
        products = Product.objects.exclude(
            pk=selected_product.id).filter(
                category=selected_category).order_by(
                    '-stock', '-popularity')[:9]

        context['categories_active'] = categories_active
        context['products'] = products
        return context


class StockDropDetailView(DetailView):
    """Renders the home page with a Products List."""
    model = StockDrop
    context_object_name = 'stockdrop'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Paginates products for the infinite scroll
        products = context['stockdrop'].products.all().order_by(
            '-stock', '-popularity')
        paginator = Paginator(products, 9)

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        # Used to hgihlight the correct collection in the navbar.
        key = self.request.path.split('/')[2]

        # Selects the active tab
        stockdrops_active = True

        context['page_obj'] = page_obj
        context['stockdrops_active'] = stockdrops_active
        context['collection_active'] = key
        return context


class CategoryDetailView(DetailView):
    """Renders the home page with a Products List."""
    model = Category
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Paginates products for the infinite scroll
        products = context['category'].products.all().order_by(
            '-stock', '-popularity')
        paginator = Paginator(products, 9)

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        # Used to hgihlight the correct collection in the navbar.
        key = self.request.path.split('/')[2]

        # Selects the active tab
        categories_active = True

        context['page_obj'] = page_obj
        context['categories_active'] = categories_active
        context['collection_active'] = key
        return context

templates/products/includes/product_box.html
{% load static %}
<!-- This is the standard template to display products in a feed.
It is used in many templates, stockdrop and category detail, the product_list homepage,
related items box, and likes_list.
It displays two ajax buttons for liking and adding to cart among other details that vary depending on
the product's characteristics, e.g. size, unique item, etc.. -->
<div class="col-12 col-md-4 p-0 infinite-item">
    <article class="card mx-0 mx-md-2 mt-3 border-0">
        <a href="{% url 'products:product-detail' product.id %}">
            <img src="{{ product.image.url }}" class="card-img-top img-fluid" alt="{{ product.name }}" />
            <!-- These display little banners that give extra info about the item. -->
            {% if product.is_unique and product.stock > 0 %}
            <span class="product-alert badge badge-pill badge-secondary">Sole Item</span>
            {% elif not product.is_unique and product.stock < 10 %}
            <span class="product-alert badge badge-pill badge-warning">Low Stock</span>
            {% elif product.stock == 0 %}
            <span class="product-alert badge badge-pill badge-danger">Sold</span>
            {% endif %}
        </a>
        <div class="row card-body mx-0 px-0 pt-1 pb-0">
            <!-- Displays product info, omitting description.
            DIsplays sizes if necessary. -->
            <a class="col-12 px-0" href="{% url 'products:product-detail' product.id %}"><h6 class="card-text text-primary heading-font mb-1 pl-1">{{ product.name|truncatechars:30 }}</h6></a>
            {% if product.size %}
            <div class="col-4 text-dark p-0 pl-0">€{{ product.price }}</div>
            <div class="col-4 text-center p-0 text-dark">Size: {{ product.size }}</div>
            {% else %}
            <div class="col-8 text-dark pl-1">€{{ product.price }}</div>
            <!-- Includes templates from the cart and likes app for the ajax buttons. -->
            {% endif %} {% if product.stock > 0 %} {% include 'cart/includes/box_cart_toggle.html' %} {% endif %} {% include 'likes/includes/box_like_toggle.html' %}
            <p class="col-12 text-white mb-0 p-0">{% for tag in product.admin_tags %} <a href="{% url 'products:product-list' %}?query={{ tag }}" class="btn btn-info rounded-sm mb-1 px-1 py-0">{{ tag }}</a> {% endfor %}</p>
        </div>
    </article>
</div>

templates/products/includes/related_products.html
<!-- A simple side-scrolling bar that displays products.
Used on empty searches, products detail pages and error pages. -->
<div class="row mx-0 mt-3">
<div class="col-12 text-center">
<h5 class="text-dark mb-0">Or take a look at these:</h5>
</div>
</div>
<div class="overflow-auto row flex-row flex-nowrap mx-0 px-5 pb-5 pt-0">
<!-- Displays using the standard product_box.html template -->
{% for product in products %}
    {% include 'products/includes/product_box.html' %}
{% endfor %}
</div>

templates/products/includes/stock_drop.html
{% load static %}
{% get_media_prefix as MEDIA_URL %}
<div id="carouselStockDrop" class="carousel slide" data-ride="carousel">
	<ol class="carousel-indicators">
    {% for number in stock_drops %}
		<li data-target="#carouselStockDrop" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active"{% endif %}></li>
    {% endfor %}
	</ol>
	<div class="carousel-inner">
        {% for collection in stock_drops %}
		<div class="carousel-item {% if forloop.first %}active{% endif %}">
			<img src="{{ collection.image.url }}" class="d-block w-100" alt="{{ collection|date:'M' }} Stock Drop">
			<div class="dark-overlay carousel-caption w-100">
				<h5 class="heading-font">{{ collection|date:'M' }} Stock Drop</h5>
				<p>{{collection.description}}</p>
			</div>
		</div>
        {% endfor %}
	</div>
	<a class="carousel-control-prev" href="#carouselStockDrop" role="button" data-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">Previous</span>
	</a>
	<a class="carousel-control-next" href="#carouselStockDrop" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">Next</span>
	</a>
</div>

templates/products/includes/stockdrop_splash.html
{% load static %} {% get_media_prefix as MEDIA_URL %}
<!-- Displays stockdrops in the carousel. Stockdrops are only shown if they have the "display" boolean as true.
This is done in the view before being passed here. They are ordered by most recent first. -->
<div id="carouselStockDrop" class="carousel slide" data-ride="carousel">
    <!-- This loops through the stockdrops, setting the first as the active one. -->
    <ol class="carousel-indicators">
        {% for number in stockdrops %}
        <li data-target="#carouselStockDrop" data-slide-to="{{ forloop.counter0 }}" {% if forloop.first %}class="active" {% endif %}></li>
        {% endfor %}
    </ol>
    <div class="carousel-inner">
        <!-- This loops through each collection of items and gives them appropriate images and links. -->
        {% for collection in stockdrops %}
        <a class="carousel-item {% if forloop.first %}active{% endif %}" href="{% url 'products:stockdrop-detail' collection.id %}">
            <img src="{{ collection.image.url }}" class="d-block w-100" alt="{{ collection.date_added|date:'M' }} StockDrop" />
            <div class="dark-overlay carousel-caption w-100">
                <h5 class="heading-font">{{ collection.date_added|date:'F' }} StockDrop</h5>
                <p>{{collection.description}}</p>
            </div>
        </a>
        {% endfor %}
    </div>
    <!-- This displays the buttons for slide selection. -->
    <a class="carousel-control-prev" href="#carouselStockDrop" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselStockDrop" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>