cart/urls.py
from django.urls import path
from .views import cart_toggle, update_cart, refresh_total, CartListView

urlpatterns = [
    path('', CartListView.as_view(), name='cart-list'),
    path('ajax/toggle/', cart_toggle, name='cart-toggle'),
    path('update/', update_cart, name='cart-update'),
    path('totals/', refresh_total, name='cart-refresh'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

# Handlers for custom error pages
handler404 = 'config.views.custom_page_not_found'
handler403 = 'config.views.custom_permission_denied'
handler400 = 'config.views.custom_bad_request'
handler500 = 'config.views.custom_server_error'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('contact/', include(('contact.urls', 'contact'),
                             namespace='contact')),
    path('cart/', include(('cart.urls', 'cart'), namespace='cart')),
    path('checkout/',
         include(('checkout.urls', 'checkout'), namespace='checkout')),
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('', include(('products.urls', 'products'), namespace='products')),
    path('users/', include(('users.urls', 'users'),
                           namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

likes/urls.py
from django.urls import path

from .views import likes_toggle, update_likes, LikesListView

urlpatterns = [
    path('', LikesListView.as_view(), name='likes-list'),
    path('ajax/toggle/', likes_toggle, name='likes-toggle'),
    path('update/', update_likes, name='likes-update'),
]

products/urls.py
from django.urls import path
from .views import (CategoryDetailView,
                    ProductListView,
                    ProductDetailView,
                    StockDropDetailView)

urlpatterns = [
    path('', ProductListView.as_view(), name="product-list"),
    path('category/<int:pk>/',
         CategoryDetailView.as_view(),
         name="category-detail"),
    path('product/<int:pk>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('stockdrop/<int:pk>/',
         StockDropDetailView.as_view(),
         name="stockdrop-detail"),
]

likes/models.py
# Create your models here.

likes/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator
from django.views.generic import ListView
from django.template import RequestContext


from django_ajax.decorators import ajax

from products.models import Product


class LikesListView(ListView):
    """View that displays all the liked products for the user."""
    model = Product
    context_object_name = 'products'
    template_name = 'likes/likes_list.html'

    def get_context_data(self, **kwargs):
        """Adds all necessary information to the context.
        Gets likes from the account if the user is logged in,
        else it creates a list from the session to display the likes.
        Sorts the list in reverse chronological if the user is logged in.
        Finally it paginates for infinite scroll."""

        context = super().get_context_data(**kwargs)

        # Sets initial variables for the context
        user = self.request.user
        context['products'] = []

        # Adds liked products ffrom the account if logged in.
        if user.is_authenticated:
            liked_products = user.userprofile.liked_products.order_by(
                '-liked__datetime_added')
            for product in liked_products:
                context['products'].append(product)

        # Otherwise it creates a list of IDs and retrieves the products from
        # the DB before adding them to the context.
        else:
            id_list = []
            session_likes = self.request.session.get('likes')

            if session_likes:
                for key in session_likes:
                    id_list.append(key)
                liked_products = Product.objects.filter(id__in=id_list)

                for product in liked_products:
                    context['products'].append(product)

        # Paginates the items for the infinite scroll feed.
        products = context['products']
        paginator = Paginator(products, 9)

        page_number = self.request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        context['page_obj'] = page_obj
        return context


@ajax
def likes_toggle(request):
    """Add or removes the specified product to likes.
    The view is Ajaxed, so it is only called by a JS file.
    It checks whether the user is authenticated or anonymous and
    runs different functions accordingly.
    The decorator converts the response to JSON format.
    It is then picked up by the JS file which completes the page effects.
    'tag' and 'message' are used to display the toasts.
    'result' is used to define the logic on the JS side."""

    if request.is_ajax and request.method == "POST":
        # Runs through a number of variables to process the ajax call.
        # If it fails, it throws an exception with a message.
        try:
            item_id = request.POST.get('item-id')
            product = get_object_or_404(Product, pk=item_id)

            # Saves the item to the profile if the user is logged in, otherwise
            # saves to the session
            if request.user.is_authenticated:
                # Retrieves the User's liked products
                user = request.user
                liked_products = user.userprofile.liked_products

                # If the product is in the list it is unliked,
                # otherwise it is liked.
                if product in liked_products.all():
                    user.userprofile.liked_products.remove(product)
                    product.save()
                    tag = 'info'
                    message = f'{product.name} unliked!'
                    result = 'unliked'
                else:
                    user.userprofile.liked_products.add(product)
                    product.save()
                    tag = 'success'
                    message = f'{product.name} liked!'
                    result = 'liked'
            
            # If the user is anonymous the items get added to the session.
            else:
                likes = request.session.get('likes', [])

                # If the product is in the list it is unliked,
                # otherwise it is liked.
                if item_id in likes:
                    likes.remove(item_id)
                    request.session['likes'] = likes
                    tag = 'info'
                    result = 'unliked'
                    message = f'{product.name} unliked!'
                else:
                    likes.append(item_id)
                    request.session['likes'] = likes
                    tag = 'success'
                    message = f'{product.name} liked!'
                    result = 'liked'

        # If none of the conditions are true, it throws an error.
        except Exception as e:
            result = 'error'
            tag = 'warning'
            message = f'Error liking item: {e}'
        return {'message': message, 'result': result, 'tag': tag}


def update_likes(request):
    """This view is used to update the likes_popover.html template.
    It is called by the JS file after it successfully recieves
    the likes_toggle view response.
    It updates the context using the same logic as the get_likes context
    processor before refreshing the template.
    The JS script then pushes the newly rendered template into
    the popover HTML."""

    # Initialises a list for use with the context
    likes = []

    # Saves the item to the profile if the user is logged in, otherwise
    # saves to the session
    user = request.user
    if user.is_authenticated:
        liked_products = user.userprofile.liked_products.order_by(
            '-liked__datetime_added')
        for product in liked_products:
            likes.append(product)

    # Creates a list of IDs and retrieves the products from
    # the DB before adding them to the context.
    else:
        id_list = []
        session_likes = request.session.get('likes')

        if session_likes:
            for key in session_likes:
                id_list.append(key)
            liked_products = Product.objects.filter(id__in=id_list)

            for product in liked_products:
                likes.append(product)

    # Pushes the new context to the page before re-rendering the template.
    RequestContext(request).push({'likes': likes})
    return render(request, 'likes/includes/likes_popover.html')

templates/likes/includes/box_like_toggle.html
{% load static %}
<!--This is the button that appears on the product_box.html template.
The toggle-form class makes it a target for the ajax functions..-->
<form class="col-2 text-center px-0 {% if product.stock == 0 %}ml-auto{% endif %} toggle-form" id="lf-{{ product.id }}" action="{% url 'likes:likes-toggle' %}" method="POST">
    {% csrf_token %}
    <!--It only sends the product ID.-->
    <input type="hidden" name="item-id" value="{{ product.id }}" />
    <button type="submit" class="btn btn-link p-0 h-100 w-100">
        <!--Selects the default icon based on whether the item is in the like context or not.
        object tags are used to display the SVG for caching.-->
        {% if product in likes %}
        <object class="box-object" id="like-svg-{{ product.id }}" type="image/svg+xml" data="{% static 'icons/heart-fill.svg' %}">
            <img id="like-img-{{ product.id }}" src="{% static 'icons/heart-fill.svg' %}" alt="Like" />
        </object>
        {% else %}
        <object class="box-object" id="like-svg-{{ product.id }}" type="image/svg+xml" data="{% static 'icons/heart.svg' %}">
            <img id="like-img-{{ product.id }}" src="{% static 'icons/heart.svg' %}" alt="Unlike" />
        </object>
        {% endif %}
    </button>
</form>

templates/likes/includes/detail_like_toggle.html
{% load static %}
<!--This is the button that appears on the product_box.html template.
The toggle-form class makes it a target for the ajax functions.-->
<form
  class="col-2 text-center px-0 toggle-form"
  id="lf-{{ product.id }}"
  action="{% url 'likes:likes-toggle' %}"
  method="POST"
>
  {% csrf_token %}
  <!--It only sends the product ID.-->
  <input type="hidden" name="item-id" value="{{ product.id }}" />
  <button type="submit" class="btn btn-link p-0 h-100 w-100">
    <!--Selects the default icon based on whether the item is in the cart or not.
        object tags are used to display the SVG for caching.-->
    {% if product in likes %}
    <object
      class="detail-object"
      id="like-svg-{{ product.id }}"
      type="image/svg+xml"
      data="{% static 'icons/heart-fill.svg' %}"
    >
      <img
        id="like-img-{{ product.id }}"
        src="{% static 'icons/heart-fill.svg' %}"
        alt="Like"
      />
    </object>
    {% else %}
    <object
      class="detail-object"
      id="like-svg-{{ product.id }}"
      type="image/svg+xml"
      data="{% static 'icons/heart.svg' %}"
    >
      <img
        id="like-img-{{ product.id }}"
        src="{% static 'icons/heart.svg' %}"
        alt="Unlike"
      />
    </object>
    {% endif %}
  </button>
</form>

templates/likes/includes/likes_popover.html
{% load static %}
<!--All content with the data-title and data-content must be escaped.-->
<a
    class="d-inline-block href-stop"
    id="like-popover"
    href="#"
    data-toggle="popover"
    data-trigger="focus"
    data-placement="bottom"
    data-html="true"
    {% if likes %}
    data-title="{% include 'likes/includes/likes_popover_title.html' %}"
    data-content="{% include 'likes/includes/likes_popover_content.html' %}"
    {% else %}
    data-title="No Likes yet."
    data-content="Checkout some wares first!"
    {% endif %}
    tabindex="0"
>
    <!--Selects the default icon based on whether there are likes or not.
    object tags are used to display the SVG for caching.-->
    {% if likes %}
    <object class="header-object" type="image/svg+xml" data="{% static 'icons/heart-fill.svg' %}">
        <img src="{% static 'icons/heart-fill.svg' %}" alt="Account" />
    </object>
    {% else %}
    <object class="header-object" type="image/svg+xml" data="{% static 'icons/heart-white.svg' %}">
        <img src="{% static 'icons/heart-white.svg' %}" alt="Account" />
    </object>
    {% endif %}
</a>

templates/likes/includes/likes_popover_content.html
{% load static %}
&lt;!--All content must be escaped. Displays the most recent liked items. Else it displays a no likes message.--&gt;
&lt;div class=&quot;list-group border-0&quot;&gt;
    {% for product in likes|slice:':3' %}
    &lt;a class=&quot;list-group-item border-0 mx-0 my-1 p-1&quot; href=&quot;{% url 'products:product-detail' product.id %}&quot;&gt;
        &lt;img src=&quot;{{ product.image.url }}&quot; class=&quot;img-fluid float-left pr-1 like-thumb&quot; alt=&quot;{{ product.name }}&quot; /&gt;
        &lt;p class=&quot;d-inline-block pb-0 mb-0&quot;&gt;{{ product.name|truncatechars:'20' }}&lt;/p&gt;
    &lt;/a&gt;
    {% endfor %}
&lt;/div&gt;

templates/likes/includes/likes_popover_title.html
&lt;!--All content must be escaped. Displays an option to go to the likes page.--&gt;
&lt;div class=&quot;text-center&quot;&gt;
    &lt;a class=&quot;text-white&quot; href=&quot;{% url 'likes:likes-list' %}&quot;&gt;&lt;p class=&quot;btn btn-secondary mb-0&quot;&gt;All Likes&lt;/p&gt;&lt;/a&gt;
&lt;/div&gt;